-- create database 

CREATE DATABASE IF NOT EXISTS NEWS;

USE NEWS;


CREATE TABLE IF NOT EXISTS AUTHORS(
    name NVARCHAR(50) NOT NULL ,
    id BIGINT PRIMARY KEY AUTO_INCREMENT
);
CREATE TABLE IF NOT EXISTS BLOGS(
    title NVARCHAR(50) NOT NULL ,
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_at DATETIME DEFAULT now(),
    content TEXT,
    short_description VARCHAR(500),
    author_id BIGINT ,
    FOREIGN KEY(author_id) REFERENCES AUTHORS(id)

);
